### ISSUE TITLE
Viewfinder for extrusion profile on camera app

### ISSUE THREAD

**Issue by ashleynewson** [oscarkey/extrusionfinder#15]
We could provide a circular viewfinder on the Android app. Zernike moments use a circular sample area, and this would encourage users to take better quality images.

The viewfinder should preferably be smaller than the total camera perspective to encourage easier view-finding, better focus, and less perspective distortion.

**Comment by as2388** [comment]
Do we need this?

**Comment by oscarkey** [comment]
Effectively added as part of profile detection on the client.
