### ISSUE TITLE
Port prototype Python image preprocessor to Java

### ISSUE THREAD

**Issue by ashleynewson** [oscarkey/extrusionfinder#19]
Convert the preprocessor functionality of the Python file at https://gist.github.com/Veedrac/8cb815038fc28702e255 to a Java class.

**Comment by MichaelHarrison-** [comment]
This issue has already been raised and the code has been written. https://github.com/oscarkey/extrusionfinder/issues/16

**Comment by ashleynewson** [comment]
The preprocessor stage (prototyped by @Veedrac in Python) has not yet been converted to Java. This issue is more specific than #16, and is a step required to convert photos into a form which may be processed by use of Zernike moments.

**Comment by ashleynewson** [comment]
The Python has been ported. Improvements to the algorithm are not part of this issue.
